### ISSUE TITLE
Not getting past black screen after IOConsoleUsers: gIOScreenLock...

### ISSUE THREAD

**Issue by kOOsi3** [jbwharris/hackintosh-msi-GL72M-7RDX#7]
Hi! jbwharris

We have the same laptop except for some HW differences. I am following the vanilla laptop guide using open core and did everything to the T with the guide. Doing the install everything works up until this point where the screen goes black after reaching IOConsoleUsers: gIOScreenLock...in verbose. Did this ever happened to you using open core?

Cobus

**Comment by jbwharris** [comment]
I don't have a specific memory of that issue, but I'm more than willing to help if possible. Someone with the same model as me is rare. I'm going to have another crack at OpenCore tonight, I've been able to get it to work, but the screen flicker makes it pretty much unusable for my purposes. I did have someone tell me that they were able to use a Skylake spoof in OpenCore, so I'm trying to see if I can get that working.

**Comment by kOOsi3** [comment]
Thank you. I re-did the whole EFI from the beginning including my config.plist with a different offline installer dmg than previously used and get exactly the same issue, black screen after gIOScreenLock. The machine stays on but nothing on the screen. As if its looking for a screen or can't initialize the iGPU properly. My device property settings are done exactly like the vanilla guide. Tried different SMBIOS and different device_id's. What I havent tried is connectin an external monitor to see if it happens too. I believe it might have something to do with my SSDT's. I might not be compiling them properly. I'm an no programmer, believe me, so some of these things are very daunting to me to try and figure out and get it right.

**Comment by jbwharris** [comment]
If you sent me your EFI I could maybe give it a try. When you say "same laptop except for some HW differences" is it a GL72M 7RDX with different processor speed? Just so I know what I'm dealing with. I know I've had decent luck with similar model MSI builds before.

**Comment by kOOsi3** [comment]
Hi! Thanks for reply. I actually managed to fix it myself. Removed some ssdt’s like EC and USBX that was seperate from eachother and used the EC-USBX-Laptop version given on vanilla guide. Also used the non preferred HD630 device ids together with the second lot of framebuffer data string 0204 to 0105. The device id was not the type with the “b” in it but just numbers. Think the “b” replaced by a 6 or so. Did the reboot and it went past to installer.

**Comment by jbwharris** [comment]
Are you planning on publishing your own repo? I'd love to see your setup either way.

**Comment by jbwharris** [comment]
@k00si3 How did you make out on this? I pushed a pretty functional OpenCore update over the weekend if you wanted to give it a try.

**Comment by kOOsi3** [comment]
It seems like it had something to do with the device_id for the iGPU. Got it working but macos very laggy and looks like there sre gpu issues. Apparently I should not have the device_id part of my device properties. Took it out, restarted and hot to login screen. During login the screen goes blank. I was told on discord that maybe i need to have device id in but with an incorrect id. I am now trying to change my config file of my boot disk EFI but having issues to get access to it from windows. Wonder if I can piggy back on the EFI on the USB to get through the login?

**Comment by jbwharris** [comment]
Take a look at the OC readme I pushed. Has instructions on changing BIOS settings to 64M, which allowed me to strip most of those patches out

**Comment by kOOsi3** [comment]
Hi! jbwharris

I am using macOS in VESA mode and can't seem to get my ogpu injecting properly. Getting the 7mb next to HD630 in "about this mac" which tells that there are no graphics acceleration. I have tried the suggested device id and AAPl,ig-platform but still not getting through login with this.Tried without device-id under device properties and not working. Don't know what to do anymore to get this ogpu sorted. Once its fixed I would move on to other stuff. This ism main priority atm.

**Comment by jbwharris** [comment]
Can you tell me what your system specs are and send a zip of your EFI folder? I'm willing to help, but need to see the full picture of what you're doing.

**Comment by kOOsi3** [comment]
Find attached my efi and DSDT.aml. 

System specs are as follow:
core i5-7300HQ
Intel HD630 igpu
Atheros ethernet controller
Realtek ALC889 audio
Wireless/BT still coming (using tp link usbwifi dongle atm)
24GB RAM 2400mhz500GB M.2 nvme SSD WD Black
macOS catalina 10.15.4

I cannot change the brightness at all, there are no flickering but no slider in display settings and buttons don't work on KB. Alt is currently my command, wish it could be changed. Currently only working in VESA mode, so the IGPU not injecting properly and is my main headache atm. If I can get it to inject then I can move on to other things like, HDMI output, trackpad buttons not working, usb mapping, power management/cpu optimisation. Hope you can help.
[EFI.zip](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/files/4670062/EFI.zip)
[DSDT.aml.zip](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/files/4670067/DSDT.aml.zip)

**Comment by jbwharris** [comment]
Is it an MSI GL62M 7RD? That model is pretty close to mine.

**Comment by jbwharris** [comment]
[EFI-modified.zip](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/files/4670913/EFI-modified.zip)
Here's my crack at making some changes. Changed the AAPL,ig-platform-id, device-id and the audio layout-id. Added in HibernationFixup.kext, NoTouchID.kext and USBInjectAll.kext. Removed the VoodooI2C.kext and VoodooI2CSynaptics.kext from the config. Then I ran it through the OpenCore Sanity Checker and it looks in pretty good shape. Give it a try and see where you get.

**Comment by kOOsi3** [comment]
Thank you. I will try but no, i have MSI GL72 7RDX model with those HW i mentioned.

**Comment by kOOsi3** [comment]
Thank you for the modified EFI, but i still get a blank screen when trying to log into macOS.

**Comment by jbwharris** [comment]
So by blank screen, you mean it shows the Apple on the screen with the progress bar, then nothing? Or are you even seeing the Apple?

**Comment by kOOsi3** [comment]
I get to the login screen in catalina. Put in my password to log in. White bar underneath starts moving. Half way through the screen turns black but machine still on. As if its trying to connect to the screen/display but not working. If i use a fake id i can log in but then the igpu shows the 7mb next to it in about this mac. 

If i do not have a device-id in device properties it does the same. I tried using the UHD630’s id recommended but get through with very bad screen flockering. I havent checked if I have acceleration though on that id.
